<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260715090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add conversation workflow domain tables for service requests, messages, audit, integrations and AI logs.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE conversations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, chatwoot_account_id INT NOT NULL, chatwoot_inbox_id INT DEFAULT NULL, chatwoot_conversation_id VARCHAR(191) NOT NULL, channel VARCHAR(64) DEFAULT NULL, contact_id VARCHAR(191) DEFAULT NULL, current_controller VARCHAR(16) NOT NULL, automation_enabled BOOLEAN DEFAULT true NOT NULL, assigned_agent_id VARCHAR(191) DEFAULT NULL, assigned_team_id VARCHAR(191) DEFAULT NULL, last_incoming_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_outgoing_message_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_conversation_chatwoot ON conversations (chatwoot_account_id, chatwoot_conversation_id)');
        $this->addSql('CREATE INDEX idx_conversation_channel ON conversations (channel)');
        $this->addSql('CREATE INDEX idx_conversation_controller ON conversations (current_controller)');
        $this->addSql('CREATE INDEX idx_conversation_automation ON conversations (automation_enabled)');
        $this->addSql('CREATE INDEX idx_conversation_agent ON conversations (assigned_agent_id)');
        $this->addSql('CREATE INDEX idx_conversation_team ON conversations (assigned_team_id)');

        $this->addSql("CREATE TABLE service_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conversation_id INT NOT NULL, legacy_attendance_protocol_id INT DEFAULT NULL, protocol VARCHAR(64) NOT NULL, service_type VARCHAR(100) DEFAULT NULL, workflow_key VARCHAR(100) NOT NULL, workflow_version INT NOT NULL, current_state VARCHAR(64) NOT NULL, current_step VARCHAR(100) DEFAULT NULL, status VARCHAR(32) NOT NULL, priority VARCHAR(32) DEFAULT NULL, sector VARCHAR(100) DEFAULT NULL, intent VARCHAR(100) DEFAULT NULL, confidence DOUBLE PRECISION DEFAULT NULL, collected_data JSON DEFAULT '{}'::json NOT NULL, context JSON DEFAULT '{}'::json NOT NULL, assigned_agent_id VARCHAR(191) DEFAULT NULL, assigned_team_id VARCHAR(191) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_service_request_protocol ON service_requests (protocol)');
        $this->addSql('CREATE INDEX idx_service_request_workflow_state ON service_requests (workflow_key, current_state)');
        $this->addSql('CREATE INDEX idx_service_request_status ON service_requests (status)');
        $this->addSql('CREATE INDEX idx_service_request_service_type ON service_requests (service_type)');
        $this->addSql('CREATE INDEX idx_service_request_intent ON service_requests (intent)');
        $this->addSql('CREATE INDEX idx_service_request_agent ON service_requests (assigned_agent_id)');
        $this->addSql('CREATE INDEX idx_service_request_team ON service_requests (assigned_team_id)');
        $this->addSql('CREATE INDEX IDX_SERVICE_REQUEST_CONVERSATION ON service_requests (conversation_id)');
        $this->addSql('CREATE INDEX IDX_SERVICE_REQUEST_LEGACY_PROTOCOL ON service_requests (legacy_attendance_protocol_id)');
        $this->addSql('ALTER TABLE service_requests ADD CONSTRAINT FK_SERVICE_REQUEST_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE service_requests ADD CONSTRAINT FK_SERVICE_REQUEST_LEGACY_PROTOCOL FOREIGN KEY (legacy_attendance_protocol_id) REFERENCES attendance_protocols (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE conversation_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conversation_id INT NOT NULL, service_request_id INT DEFAULT NULL, chatwoot_message_id VARCHAR(191) DEFAULT NULL, direction VARCHAR(16) NOT NULL, sender_type VARCHAR(32) NOT NULL, sender_id VARCHAR(191) DEFAULT NULL, message_type VARCHAR(64) DEFAULT NULL, content TEXT DEFAULT NULL, attachments JSON DEFAULT '[]'::json NOT NULL, delivery_status VARCHAR(64) DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, metadata JSON DEFAULT '{}'::json NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_conversation_chatwoot_message ON conversation_messages (conversation_id, chatwoot_message_id)');
        $this->addSql('CREATE INDEX idx_conversation_message_direction ON conversation_messages (direction)');
        $this->addSql('CREATE INDEX idx_conversation_message_sender_type ON conversation_messages (sender_type)');
        $this->addSql('CREATE INDEX idx_conversation_message_type ON conversation_messages (message_type)');
        $this->addSql('CREATE INDEX idx_conversation_message_created_at ON conversation_messages (created_at)');
        $this->addSql('CREATE INDEX IDX_CONVERSATION_MESSAGE_CONVERSATION ON conversation_messages (conversation_id)');
        $this->addSql('CREATE INDEX IDX_CONVERSATION_MESSAGE_REQUEST ON conversation_messages (service_request_id)');
        $this->addSql('ALTER TABLE conversation_messages ADD CONSTRAINT FK_CONVERSATION_MESSAGE_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE conversation_messages ADD CONSTRAINT FK_CONVERSATION_MESSAGE_REQUEST FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE request_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, service_request_id INT DEFAULT NULL, conversation_id INT DEFAULT NULL, event_type VARCHAR(100) NOT NULL, transition_name VARCHAR(100) DEFAULT NULL, from_state VARCHAR(64) DEFAULT NULL, to_state VARCHAR(64) DEFAULT NULL, actor_type VARCHAR(32) NOT NULL, actor_id VARCHAR(191) DEFAULT NULL, reason TEXT DEFAULT NULL, result VARCHAR(64) DEFAULT NULL, metadata JSON DEFAULT '{}'::json NOT NULL, previous_event_hash VARCHAR(64) DEFAULT NULL, event_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_request_event_type ON request_events (event_type)');
        $this->addSql('CREATE INDEX idx_request_event_transition ON request_events (transition_name)');
        $this->addSql('CREATE INDEX idx_request_event_actor_type ON request_events (actor_type)');
        $this->addSql('CREATE INDEX idx_request_event_created_at ON request_events (created_at)');
        $this->addSql('CREATE INDEX IDX_REQUEST_EVENT_REQUEST ON request_events (service_request_id)');
        $this->addSql('CREATE INDEX IDX_REQUEST_EVENT_CONVERSATION ON request_events (conversation_id)');
        $this->addSql('ALTER TABLE request_events ADD CONSTRAINT FK_REQUEST_EVENT_REQUEST FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE request_events ADD CONSTRAINT FK_REQUEST_EVENT_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE external_integration_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, service_request_id INT DEFAULT NULL, conversation_id INT DEFAULT NULL, system_name VARCHAR(100) NOT NULL, operation VARCHAR(100) NOT NULL, request_reference VARCHAR(191) DEFAULT NULL, response_status VARCHAR(64) DEFAULT NULL, duration_ms INT DEFAULT NULL, success BOOLEAN NOT NULL, error_code VARCHAR(100) DEFAULT NULL, request_metadata JSON DEFAULT '{}'::json NOT NULL, response_metadata JSON DEFAULT '{}'::json NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_external_integration_system ON external_integration_logs (system_name)');
        $this->addSql('CREATE INDEX idx_external_integration_operation ON external_integration_logs (operation)');
        $this->addSql('CREATE INDEX idx_external_integration_success ON external_integration_logs (success)');
        $this->addSql('CREATE INDEX idx_external_integration_created_at ON external_integration_logs (created_at)');
        $this->addSql('CREATE INDEX IDX_EXTERNAL_INTEGRATION_REQUEST ON external_integration_logs (service_request_id)');
        $this->addSql('CREATE INDEX IDX_EXTERNAL_INTEGRATION_CONVERSATION ON external_integration_logs (conversation_id)');
        $this->addSql('ALTER TABLE external_integration_logs ADD CONSTRAINT FK_EXTERNAL_INTEGRATION_REQUEST FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE external_integration_logs ADD CONSTRAINT FK_EXTERNAL_INTEGRATION_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE ai_execution_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, service_request_id INT DEFAULT NULL, conversation_id INT DEFAULT NULL, model VARCHAR(100) NOT NULL, model_version VARCHAR(100) DEFAULT NULL, prompt_key VARCHAR(100) DEFAULT NULL, prompt_version INT DEFAULT NULL, operation VARCHAR(100) NOT NULL, input_hash VARCHAR(64) DEFAULT NULL, structured_result JSON DEFAULT '{}'::json NOT NULL, confidence DOUBLE PRECISION DEFAULT NULL, knowledge_sources JSON DEFAULT '[]'::json NOT NULL, duration_ms INT DEFAULT NULL, success BOOLEAN NOT NULL, error_code VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_ai_execution_operation ON ai_execution_logs (operation)');
        $this->addSql('CREATE INDEX idx_ai_execution_model ON ai_execution_logs (model)');
        $this->addSql('CREATE INDEX idx_ai_execution_success ON ai_execution_logs (success)');
        $this->addSql('CREATE INDEX idx_ai_execution_created_at ON ai_execution_logs (created_at)');
        $this->addSql('CREATE INDEX IDX_AI_EXECUTION_REQUEST ON ai_execution_logs (service_request_id)');
        $this->addSql('CREATE INDEX IDX_AI_EXECUTION_CONVERSATION ON ai_execution_logs (conversation_id)');
        $this->addSql('ALTER TABLE ai_execution_logs ADD CONSTRAINT FK_AI_EXECUTION_REQUEST FOREIGN KEY (service_request_id) REFERENCES service_requests (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ai_execution_logs ADD CONSTRAINT FK_AI_EXECUTION_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES conversations (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ai_execution_logs DROP CONSTRAINT FK_AI_EXECUTION_CONVERSATION');
        $this->addSql('ALTER TABLE ai_execution_logs DROP CONSTRAINT FK_AI_EXECUTION_REQUEST');
        $this->addSql('ALTER TABLE external_integration_logs DROP CONSTRAINT FK_EXTERNAL_INTEGRATION_CONVERSATION');
        $this->addSql('ALTER TABLE external_integration_logs DROP CONSTRAINT FK_EXTERNAL_INTEGRATION_REQUEST');
        $this->addSql('ALTER TABLE request_events DROP CONSTRAINT FK_REQUEST_EVENT_CONVERSATION');
        $this->addSql('ALTER TABLE request_events DROP CONSTRAINT FK_REQUEST_EVENT_REQUEST');
        $this->addSql('ALTER TABLE conversation_messages DROP CONSTRAINT FK_CONVERSATION_MESSAGE_REQUEST');
        $this->addSql('ALTER TABLE conversation_messages DROP CONSTRAINT FK_CONVERSATION_MESSAGE_CONVERSATION');
        $this->addSql('ALTER TABLE service_requests DROP CONSTRAINT FK_SERVICE_REQUEST_LEGACY_PROTOCOL');
        $this->addSql('ALTER TABLE service_requests DROP CONSTRAINT FK_SERVICE_REQUEST_CONVERSATION');
        $this->addSql('DROP TABLE ai_execution_logs');
        $this->addSql('DROP TABLE external_integration_logs');
        $this->addSql('DROP TABLE request_events');
        $this->addSql('DROP TABLE conversation_messages');
        $this->addSql('DROP TABLE service_requests');
        $this->addSql('DROP TABLE conversations');
    }
}