<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260607120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Chatwoot account and webhook event tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE chatwoot_accounts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(191) NOT NULL, base_url VARCHAR(255) NOT NULL, api_token VARCHAR(512) NOT NULL, webhook_secret VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE chatwoot_message_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, chatwoot_account_id INT NOT NULL, event_type VARCHAR(100) DEFAULT NULL, external_conversation_id VARCHAR(191) DEFAULT NULL, external_message_id VARCHAR(191) DEFAULT NULL, payload_hash VARCHAR(64) NOT NULL, raw_payload JSON NOT NULL, processing_status VARCHAR(32) NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CHATWOOT_EVENTS_ACCOUNT ON chatwoot_message_events (chatwoot_account_id)');
        $this->addSql('CREATE INDEX idx_chatwoot_events_status ON chatwoot_message_events (processing_status)');
        $this->addSql('CREATE INDEX idx_chatwoot_events_type ON chatwoot_message_events (event_type)');
        $this->addSql('CREATE INDEX idx_chatwoot_events_created_at ON chatwoot_message_events (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_chatwoot_event_idempotency ON chatwoot_message_events (chatwoot_account_id, event_type, external_conversation_id, external_message_id, payload_hash)');
        $this->addSql('ALTER TABLE chatwoot_message_events ADD CONSTRAINT FK_CHATWOOT_EVENTS_ACCOUNT FOREIGN KEY (chatwoot_account_id) REFERENCES chatwoot_accounts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE chatwoot_message_events DROP CONSTRAINT FK_CHATWOOT_EVENTS_ACCOUNT');
        $this->addSql('DROP TABLE chatwoot_message_events');
        $this->addSql('DROP TABLE chatwoot_accounts');
    }
}
