<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260624120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create SIGI attendance protocol tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE protocol_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sequence_scope VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql("INSERT INTO protocol_settings (sequence_scope, created_at) VALUES ('daily', CURRENT_TIMESTAMP)");
        $this->addSql('CREATE TABLE attendance_protocols (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, protocol_code VARCHAR(32) NOT NULL, sequence_scope VARCHAR(16) NOT NULL, sequence_date DATE NOT NULL, sequence_number INT NOT NULL, chatwoot_conversation_id VARCHAR(191) NOT NULL, chatwoot_contact_id VARCHAR(191) DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, contact_handle VARCHAR(255) DEFAULT NULL, source_channel VARCHAR(100) DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, status VARCHAR(64) DEFAULT NULL, labels JSON NOT NULL, labels_text TEXT DEFAULT NULL, responsible_team VARCHAR(191) DEFAULT NULL, responsible_agent VARCHAR(191) DEFAULT NULL, priority VARCHAR(64) DEFAULT NULL, protocol_note_sent BOOLEAN NOT NULL, protocol_note_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_attendance_protocol_code ON attendance_protocols (protocol_code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_attendance_chatwoot_conversation ON attendance_protocols (chatwoot_conversation_id)');
        $this->addSql('CREATE INDEX idx_attendance_protocol_status ON attendance_protocols (status)');
        $this->addSql('CREATE INDEX idx_attendance_protocol_channel ON attendance_protocols (source_channel)');
        $this->addSql('CREATE INDEX idx_attendance_protocol_team ON attendance_protocols (responsible_team)');
        $this->addSql('CREATE INDEX idx_attendance_protocol_agent ON attendance_protocols (responsible_agent)');
        $this->addSql('CREATE INDEX idx_attendance_protocol_priority ON attendance_protocols (priority)');
        $this->addSql('CREATE INDEX idx_attendance_protocol_created_at ON attendance_protocols (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE attendance_protocols');
        $this->addSql('DROP TABLE protocol_settings');
    }
}
