doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: '~^(addresses|address_types|attendance_protocols|cities|comment|contact_issue_types|contact_statuses|contact_types|countries|coverage_types|interaction_statuses|interaction_threads|chatwoot_accounts|chatwoot_message_events|mesoregions|microregions|organizations|organization_addresses|organization_contacts|organization_contact_interactions|organization_coverages|organization_thematic_areas|organization_types|persons|person_addresses|person_contacts|person_contact_interactions|person_coverages|person_organizations|person_organization_roles|person_thematic_areas|post|post_tag|protocol_settings|regions|response_types|roles|states|tag|thematic_areas|users|doctrine_migration_versions)$~'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'

    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity

        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
